name := "Vertx scala test http"

version := "0.1"

scalaVersion := "2.12.4"

libraryDependencies += "io.vertx" % "vertx-codegen"                            % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-lang-scala"                        % "3.5.0"
libraryDependencies += "io.vertx" %  "vertx-hazelcast"                         % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-scala"                         % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-mqtt-server-scala"                 % "3.5.0"

/*libraryDependencies += "io.vertx" %% "vertx-sql-common-scala"                  % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-bridge-common-scala"               % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-jdbc-client-scala"                 % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-mongo-client-scala"                % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-mongo-service-scala"               % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-common-scala"                 % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-shiro-scala"                  % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-htdigest-scala"               % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-oauth2-scala"                 % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-mongo-scala"                  % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-jwt-scala"                    % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-auth-jdbc-scala"                   % "3.5.0"
*/
libraryDependencies += "io.vertx" %% "vertx-web-common-scala"                  % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-client-scala"                  % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-sockjs-service-proxy-scala"        % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-templ-freemarker-scala"        % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-templ-handlebars-scala"        % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-templ-jade-scala"              % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-templ-mvel-scala"              % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-templ-pebble-scala"            % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-web-templ-thymeleaf-scala"         % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-mysql-postgresql-client-scala"     % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-mail-client-scala"                 % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-rabbitmq-client-scala"             % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-redis-client-scala"                % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-stomp-scala"                       % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-tcp-eventbus-bridge-scala"         % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-amqp-bridge-scala"                 % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-dropwizard-metrics-scala"          % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-hawkular-metrics-scala"            % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-shell-scala"                       % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-kafka-client-scala"                % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-circuit-breaker-scala"             % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-config-scala"                      % "3.5.0"
libraryDependencies += "io.vertx" %% "vertx-service-discovery-scala"           % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-git-scala"                  % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-hocon-scala"                % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-kubernetes-configmap-scala" % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-redis-scala"                % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-spring-config-server-scala" % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-yaml-scala"                 % "3.5.0"
//libraryDependencies += "io.vertx" %% "vertx-config-zookeeper-scala"            % "3.5.0"
libraryDependencies += "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.9.2"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.4"